import json
from dataclasses import dataclass, asdict
from typing import Any, Dict, Optional

from openai import OpenAI


@dataclass
class RewardResult:
    total_reward: float
    overall_score: float
    accuracy: float
    task_match: float
    useful_properties: float
    clarity: float
    hallucination: float
    too_verbose: float
    irrelevant_instructions: float
    properties_detected: Dict[str, bool]
    feedback: str
    usage: Dict[str, int]
    raw_judge_json: Dict[str, Any]


class PromptRewardModel:
    """
    Reward model for prompt optimization on coding tasks.

    One API call returns:
    - scalar scores
    - property flags
    - penalties
    - reflection feedback

    Then we compute the final reward locally so you can change weights anytime.
    """

    def __init__(
        self,
        api_key: str,
        model: str = "gpt-5.4",
        w_accuracy: float = 0.50,
        w_task_match: float = 0.25,
        w_properties: float = 0.15,
        w_clarity: float = 0.10,
        w_hallucination: float = 0.10,
        w_too_verbose: float = 0.05,
        w_irrelevant: float = 0.05,
        token_penalty_weight: float = 0.0,
    ) -> None:
        self.client = OpenAI(api_key=api_key)
        self.model = model

        self.w_accuracy = w_accuracy
        self.w_task_match = w_task_match
        self.w_properties = w_properties
        self.w_clarity = w_clarity
        self.w_hallucination = w_hallucination
        self.w_too_verbose = w_too_verbose
        self.w_irrelevant = w_irrelevant
        self.token_penalty_weight = token_penalty_weight

    def evaluate(
        self,
        coding_task: str,
        optimized_prompt: str,
        target_llm_output: str,
        reference_solution: Optional[str] = None,
        execution_result: Optional[str] = None,
    ) -> RewardResult:
        """
        Evaluate one prompt on one coding task.

        Args:
            coding_task: The programming problem statement.
            optimized_prompt: The prompt produced by your trainable policy.
            target_llm_output: The solution generated by the target LLM using that prompt.
            reference_solution: Optional gold/reference solution.
            execution_result: Optional unit test / compile / runtime result string.

        Returns:
            RewardResult with scalar reward + feedback.
        """

        schema = {
            "name": "prompt_reward_evaluation",
            "schema": {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "overall_score": {
                        "type": "number",
                        "minimum": 0.0,
                        "maximum": 1.0,
                        "description": "Overall evaluator score for how effective the prompt was."
                    },
                    "subscores": {
                        "type": "object",
                        "additionalProperties": False,
                        "properties": {
                            "accuracy": {"type": "number", "minimum": 0.0, "maximum": 1.0},
                            "task_match": {"type": "number", "minimum": 0.0, "maximum": 1.0},
                            "useful_properties": {"type": "number", "minimum": 0.0, "maximum": 1.0},
                            "clarity": {"type": "number", "minimum": 0.0, "maximum": 1.0},
                        },
                        "required": ["accuracy", "task_match", "useful_properties", "clarity"],
                    },
                    "properties_detected": {
                        "type": "object",
                        "additionalProperties": False,
                        "properties": {
                            "step_by_step_guidance": {"type": "boolean"},
                            "edge_case_awareness": {"type": "boolean"},
                            "structured_output_request": {"type": "boolean"},
                            "correctness_focus": {"type": "boolean"},
                            "efficiency_awareness": {"type": "boolean"},
                            "testing_request": {"type": "boolean"},
                        },
                        "required": [
                            "step_by_step_guidance",
                            "edge_case_awareness",
                            "structured_output_request",
                            "correctness_focus",
                            "efficiency_awareness",
                            "testing_request",
                        ],
                    },
                    "penalties": {
                        "type": "object",
                        "additionalProperties": False,
                        "properties": {
                            "hallucination": {"type": "number", "minimum": 0.0, "maximum": 1.0},
                            "too_verbose": {"type": "number", "minimum": 0.0, "maximum": 1.0},
                            "irrelevant_instructions": {"type": "number", "minimum": 0.0, "maximum": 1.0},
                        },
                        "required": ["hallucination", "too_verbose", "irrelevant_instructions"],
                    },
                    "feedback": {
                        "type": "string",
                        "description": "Short reflection explaining how to improve the prompt next time."
                    },
                },
                "required": [
                    "overall_score",
                    "subscores",
                    "properties_detected",
                    "penalties",
                    "feedback",
                ],
            },
            "type": "json_schema",
            "strict": True,
        }

        system_prompt = """You are a strict evaluator for reinforcement-learning-based prompt optimization.

Your task is to judge how good an optimized prompt is for helping a target LLM solve a coding task.

Scoring dimensions:
1. accuracy:
   Evaluate whether the target LLM output actually solves the coding task.
    Scoring priority:
    1. If execution or unit-test results are provided, use them as the primary signal.
    2. If a reference solution is provided, compare against it for semantic correctness and completeness.
    3. Otherwise, judge whether the solution is logically correct, complete, handles important edge cases, and avoids incorrect or invented code.
    
    Give a low score if:
    - the code does not solve the requested task,
    - important parts are missing,
    - edge cases are ignored when relevant,
    - the code contains invalid logic, non-existent APIs, or false claims.

2. task_match:
   How well the prompt matches the specific coding task and constraints.

3. useful_properties:
   Whether the prompt contains useful coding-oriented guidance such as:
   - step-by-step guidance
   - edge-case awareness
   - correctness focus
   - structured output request
   - efficiency awareness when relevant
   - testing/verification request

4. clarity:
   How clear, concise, coherent, and actionable the prompt is.

Penalties:
- hallucination:
  Penalize invented APIs, false claims, unsupported assumptions, or content not grounded in the task.
- too_verbose:
  Penalize bloated prompts that add unnecessary length.
- irrelevant_instructions:
  Penalize instructions unrelated to solving the coding task.

Feedback:
Return a short reflection message with concrete suggestions to improve the prompt in the next step.

Important:
- Be strict.
- Return only the requested structured JSON.
- Scores must be in [0, 1].
"""

        user_payload = {
            "coding_task": coding_task,
            "optimized_prompt": optimized_prompt,
            "target_llm_output": target_llm_output,
            "reference_solution": reference_solution,
            "execution_result": execution_result,
        }

        response = self.client.responses.create(
            model=self.model,
            input=[
                {"role": "system", "content": [{"type": "input_text", "text": system_prompt}]},
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "input_text",
                            "text": json.dumps(user_payload, ensure_ascii=False, indent=2),
                        }
                    ],
                },
            ],
            text={
                "format": schema
            },
        )

        parsed = json.loads(response.output_text)

        subscores = parsed["subscores"]
        penalties = parsed["penalties"]

        usage = {
            "input_tokens": getattr(response.usage, "input_tokens", 0) if response.usage else 0,
            "output_tokens": getattr(response.usage, "output_tokens", 0) if response.usage else 0,
            "total_tokens": getattr(response.usage, "total_tokens", 0) if response.usage else 0,
        }

        token_penalty = self.token_penalty_weight * usage["total_tokens"]

        total_reward = (
            self.w_accuracy * subscores["accuracy"]
            + self.w_task_match * subscores["task_match"]
            + self.w_properties * subscores["useful_properties"]
            + self.w_clarity * subscores["clarity"]
            - self.w_hallucination * penalties["hallucination"]
            - self.w_too_verbose * penalties["too_verbose"]
            - self.w_irrelevant * penalties["irrelevant_instructions"]
            - token_penalty
        )

        return RewardResult(
            total_reward=total_reward,
            overall_score=parsed["overall_score"],
            accuracy=subscores["accuracy"],
            task_match=subscores["task_match"],
            useful_properties=subscores["useful_properties"],
            clarity=subscores["clarity"],
            hallucination=penalties["hallucination"],
            too_verbose=penalties["too_verbose"],
            irrelevant_instructions=penalties["irrelevant_instructions"],
            properties_detected=parsed["properties_detected"],
            feedback=parsed["feedback"],
            usage=usage,
            raw_judge_json=parsed,
        )